# Generated by Django 5.2.1 on 2025-05-26 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_rename_gamesread_gamesplayed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamesPlayed',
            new_name='GamesBeaten',
        ),
    ]
