# Generated by Django 5.2.1 on 2025-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0003_rename_gamesplayed_gamesbeaten'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroGameCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('console', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
