# Generated by Django 5.2.1 on 2025-05-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0004_retrogamecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueAchievementsGameCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
