# Generated by Django 5.2.1 on 2025-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0005_trueachievementsgamecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBGameCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
