# Generated by Django 5.2.1 on 2025-05-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0006_igdbgamecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hours_completionist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='hours_main_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='hours_main_story',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
