# Generated by Django 5.2.1 on 2025-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0007_game_hours_completionist_game_hours_main_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
