# Generated by Django 5.2.1 on 2025-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0008_alter_game_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hours',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
