# Generated by Django 5.2.1 on 2025-05-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0009_remove_game_hours_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='image_url',
        ),
    ]
