# Generated by Django 5.2.1 on 2025-05-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0011_gameprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameProgressTracker',
        ),
    ]
