# Generated by Django 5.2.1 on 2025-05-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0012_delete_gameprogresstracker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_available', models.PositiveIntegerField(help_text='Total available in the game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectible_types', to='gaming.game')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollectibleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.PositiveIntegerField(default=0)),
                ('collectible_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.collectibletype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'collectible_type')},
            },
        ),
    ]
