# Generated by Django 5.2.1 on 2025-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0014_retroconsole_retrogameentry_game_achievements_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='mastered',
            field=models.BooleanField(default=False),
        ),
    ]
