[project]
name = "household-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-bootstrap5>=24.3",
    "django>=5.1.2",
]
