# Generated by Django 5.1.2 on 2024-10-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_name', models.CharField(max_length=20)),
                ('dishes_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_name', models.CharField(max_length=20)),
                ('trash_cost', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chore',
        ),
    ]
