# Generated by Django 5.2.1 on 2025-06-14 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_payoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='chore_category',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='text',
        ),
        migrations.AddField(
            model_name='chore',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chores.chorecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
