# Generated by Django 5.1.2 on 2024-10-21 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_dishes_trash_delete_chore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_one_laborer', models.CharField(max_length=20)),
                ('bathroom_one_cost', models.IntegerField()),
                ('bathroom_one_timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_two_laborer', models.CharField(max_length=20)),
                ('bathroom_two_cost', models.IntegerField()),
                ('bathroom_two_timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dust_laborer', models.CharField(max_length=20)),
                ('dust_cost', models.IntegerField()),
                ('dust_timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Playroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playroom_laborer', models.CharField(max_length=20)),
                ('playroom_cost', models.IntegerField()),
                ('playroom_timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuum_laborer', models.CharField(max_length=20)),
                ('vacuum_cost', models.IntegerField()),
                ('vacuum_timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='dishes_name',
            new_name='dishes_laborer',
        ),
        migrations.RenameField(
            model_name='trash',
            old_name='trash_name',
            new_name='trash_laborer',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishes_timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trash',
            name='trash_timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
