# Generated by Django 5.1.2 on 2024-10-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choreentry_chores_delete_chore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreentry',
            name='chore_entry',
        ),
    ]
