# Generated by Django 5.2.1 on 2025-06-14 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_remove_chore_chore_category_remove_chore_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreentry',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
