# Generated by Django 5.1.2 on 2024-10-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_bathroom_one_bathroom_two_dust_playroom_vacuum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bathroom_one',
            name='bathroom_one_timestamp',
        ),
        migrations.RemoveField(
            model_name='bathroom_two',
            name='bathroom_two_timestamp',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='dishes_timestamp',
        ),
        migrations.RemoveField(
            model_name='dust',
            name='dust_timestamp',
        ),
        migrations.RemoveField(
            model_name='playroom',
            name='playroom_timestamp',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='trash_timestamp',
        ),
        migrations.RemoveField(
            model_name='vacuum',
            name='vacuum_timestamp',
        ),
    ]
