# Generated by Django 5.1.2 on 2024-10-23 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_remove_choreentry_chore_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choreentry',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='choreentry',
            name='chore',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chores',
            name='text',
            field=models.CharField(max_length=20),
        ),
    ]
