# Generated by Django 5.1.2 on 2024-10-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_datetimefield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_done', models.CharField(max_length=20)),
            ],
        ),
    ]
