# Generated by Django 5.1.2 on 2024-10-21 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_chorelogging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'chore_entries',
            },
        ),
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bathroom_one',
        ),
        migrations.DeleteModel(
            name='Bathroom_two',
        ),
        migrations.DeleteModel(
            name='ChoreLogging',
        ),
        migrations.DeleteModel(
            name='DateTimeField',
        ),
        migrations.DeleteModel(
            name='Dishes',
        ),
        migrations.DeleteModel(
            name='Dust',
        ),
        migrations.DeleteModel(
            name='Playroom',
        ),
        migrations.DeleteModel(
            name='Trash',
        ),
        migrations.DeleteModel(
            name='Vacuum',
        ),
        migrations.AddField(
            model_name='choreentry',
            name='chore_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.chores'),
        ),
    ]
