# Generated by Django 5.1.2 on 2024-10-24 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_alter_choreentry_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choreentry',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='choreentry',
            name='chore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.chores'),
        ),
    ]
