# Generated by Django 5.1.2 on 2024-10-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_rename_name_choreentry_user_alter_choreentry_chore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreentry',
            name='chore',
        ),
    ]
