# Generated by Django 5.1.2 on 2024-10-21 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_choreentry_chores_delete_bathroom_one_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chores',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='chores',
            name='owner',
        ),
        migrations.AddField(
            model_name='chores',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choreentry',
            name='chore_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
