# Generated by Django 5.1.2 on 2024-10-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_alter_choreentry_chore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choreentry',
            options={'permissions': (('can_log_chore', 'Can Log Chore'),), 'verbose_name_plural': 'chore_entries'},
        ),
    ]
