# Generated by Django 5.1.2 on 2025-04-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'book_categories',
            },
        ),
    ]
