# Generated by Django 5.1.2 on 2025-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0003_book_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
