# Generated by Django 5.2.1 on 2025-05-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0005_bookprogresstracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordsRead',
        ),
    ]
