# Generated by Django 5.2.1 on 2025-05-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0006_delete_wordsread'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='book_club.book')),
            ],
        ),
    ]
