# Generated by Django 5.2.1 on 2025-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0007_bookmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
