# Generated by Django 5.2.1 on 2025-05-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0008_book_pages_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmetadata',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
