# Generated by Django 5.2.1 on 2025-05-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0009_bookmetadata_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='text',
            new_name='title',
        ),
    ]
