# Generated by Django 5.2.1 on 2025-06-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0012_bookseries_alter_book_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmetadata',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmetadata',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
