# Generated by Django 5.2.1 on 2025-06-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0013_alter_bookmetadata_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmetadata',
            name='pages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
