# Generated by Django 5.2.1 on 2025-06-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0015_alter_book_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmetadata',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
