# Generated by Django 5.1.2 on 2025-04-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_xplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.PositiveIntegerField(default=50)),
                ('exponent', models.FloatField(default=0.75)),
            ],
            options={
                'verbose_name_plural': 'XP Settings',
            },
        ),
    ]
