# Generated by Django 5.1.2 on 2025-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_xpsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='userstats',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
