# Generated by Django 5.1.2 on 2025-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userstats_last_updated_alter_userstats_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='xp_per_wage_earned',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='xp_per_word',
            field=models.FloatField(default=0.1),
        ),
    ]
