# Generated by Django 5.1.2 on 2025-04-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_xpsettings_updated_at_xpsettings_xp_per_wage_earned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpsettings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='xpsettings',
            name='xp_per_wage_earned',
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='xp_per_chore_wage',
            field=models.FloatField(default=0.0, help_text='XP awarded per wage unit earned (chores)'),
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='xp_per_word',
            field=models.FloatField(default=0.0, help_text='XP awarded per word read (book club)'),
        ),
    ]
