# Generated by Django 5.1.2 on 2025-04-28 02:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_xpsettings_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='level',
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='xp_per_chore_wage',
            field=models.DecimalField(decimal_places=6, default=Decimal('10.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='xp_per_word',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.002'), max_digits=10),
        ),
    ]
