# Generated by Django 5.1.2 on 2025-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userstats_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='words_read',
            field=models.IntegerField(default=0),
        ),
    ]
