# Generated by Django 5.2.1 on 2025-05-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_badge_xpsettings_xp_per_book_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreXPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_level', models.PositiveIntegerField(unique=True)),
                ('chore_xp_required', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['chore_level'],
            },
        ),
        migrations.CreateModel(
            name='ReadingXPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_level', models.PositiveIntegerField(unique=True)),
                ('reading_xp_required', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['reading_level'],
            },
        ),
        migrations.CreateModel(
            name='XPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_level', models.PositiveIntegerField(unique=True)),
                ('xp_required', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['overall_level'],
            },
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='xp',
        ),
        migrations.AddField(
            model_name='userstats',
            name='chore_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userstats',
            name='chore_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='overall_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userstats',
            name='overall_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='reading_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userstats',
            name='reading_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='chore_base',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='chore_exponent',
            field=models.FloatField(default=1.25),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='reading_base',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='reading_exponent',
            field=models.FloatField(default=1.25),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='words_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='base',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='exponent',
            field=models.FloatField(default=1.25),
        ),
    ]
