# Generated by Django 5.2.1 on 2025-05-25 22:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chorexptable_readingxptable_xptable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingXPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaming_level', models.PositiveIntegerField(unique=True)),
                ('gaming_xp_required', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['gaming_level'],
            },
        ),
        migrations.AddField(
            model_name='userstats',
            name='gaming_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userstats',
            name='gaming_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='gaming_base',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='gaming_exponent',
            field=models.FloatField(default=1.25),
        ),
        migrations.AddField(
            model_name='xpsettings',
            name='xp_per_hour_gamed',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='badge',
            name='app_label',
            field=models.CharField(choices=[('chores', 'Chores'), ('book_club', 'Books'), ('gaming', 'Gaming')], help_text='Select the app/module this badge applies to.', max_length=50),
        ),
    ]
