# Generated by Django 5.2.1 on 2025-05-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_gamingxptable_userstats_gaming_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='hours_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
