# Generated by Django 5.2.1 on 2025-05-26 01:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userstats_hours_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpsettings',
            name='xp_per_game_beaten',
            field=models.DecimalField(decimal_places=6, default=Decimal('20'), max_digits=10),
        ),
    ]
