# Generated by Django 5.2.1 on 2025-05-26 06:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_xpsettings_xp_per_game_beaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpsettings',
            name='xp_per_chore_wage',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='xp_per_game_beaten',
            field=models.DecimalField(decimal_places=1, default=Decimal('20'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='xp_per_hour_gamed',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='xpsettings',
            name='xp_per_word',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.002'), max_digits=10),
        ),
    ]
