# Generated by Django 5.2.1 on 2025-05-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_xpsettings_xp_per_chore_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='ra_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='xbl_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
