# Generated by Django 5.2.1 on 2025-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userstats_ra_username_userstats_xbl_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='reading_wpm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
