# Generated by Django 5.1.2 on 2024-10-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_main', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Notes',
        ),
    ]
