# Generated by Django 5.1.2 on 2024-10-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_main', '0004_rename_topic_entry_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
