# Generated by Django 5.1.2 on 2024-10-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_main', '0005_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='notes',
            new_name='note',
        ),
    ]
